name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'version'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'version'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - run: sbt -v lint
  test:
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 11, 17, 19 ]
        scala: [ 2.13.13, 3.3.1 ]
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    name: "Run tests with JDK ${{ matrix.jdk }}, Scala ${{ matrix.scala }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: sbt test
        run: sbt -v ++${{ matrix.scala }} test
  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
